config/routes.rb
Picbook::Application.routes.draw do

  resources :users

  resources :userpanels
  resources :sessions
  resources :password_resets
  resources :albums
  resources :images
  resources :userprofiles

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "usercp" => "users#usercp", :as => "usercp"

  root :to => 'welcome#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :description, :name, :users_id

  def to_param
    "#{id}-#{name}"
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_filter :require_login, :only => [:new, :edit, :index]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(params[:album])

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
    <div class="field">
      <%= f.hidden_field :users_id, :value => self.current_user.id %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h1>Listing albums</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>


  <% available_albums = Album.find_all_by_users_id(self.current_user.id) %>

<% available_albums.each do |album| %>
<tr>
  <td><%= album.name %></td>
  <td><%= album.description %></td>

  <td><%= link_to 'Show', album %></td>
  <td><%= link_to 'Edit', edit_album_path(album) %></td>
  <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>
<% end %>
</table>

<br />

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<head>
  <%= stylesheet_link_tag "albums", :media => "all" %>
  <script type="text/javascript" charset="utf-8">
      $(document).ready(function(){
          $("area[rel^='prettyPhoto']").prettyPhoto();
      });
  </script>
</head>

<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @album.name %>
</p>

<p>
  <b>Description:</b>
  <%= @album.description %>
</p>

<div id="content2">
  <ul class="gallery clearfix">
    <br/>
    <li><a href="../assets/fullscreen/1.jpg" rel="prettyPhoto[gallery1]" title="Malte stinkt."><img src="../assets/thumbnails/t_1.jpg" width="60" height="60" alt="Red round shape" /></a></li>
    <li><a href="../assets/fullscreen/2.jpg" rel="prettyPhoto[gallery1]"><img src="../assets/thumbnails/t_2.jpg" width="60" height="60" alt="Nice building" /></a></li>
    <li><a href="../assets/fullscreen/3.jpg" rel="prettyPhoto[gallery1]"><img src="../assets/thumbnails/t_3.jpg" width="60" height="60" alt="Fire!" /></a></li>
    <li><a href="../assets/fullscreen/4.jpg" rel="prettyPhoto[gallery1]"><img src="../assets/thumbnails/t_4.jpg" width="60" height="60" alt="Rock climbing" /></a></li>
    <li><a href="../assets/fullscreen/5.jpg" rel="prettyPhoto[gallery1]"><img src="../assets/thumbnails/t_5.jpg" width="60" height="60" alt="Fly kite, fly!" /></a></li>
    <br/>
  </ul>
  </div>

<script type="text/javascript" charset="utf-8">
    $(document).ready(function(){
        $("area[rel^='prettyPhoto']").prettyPhoto();

        $(".gallery:first a[rel^='prettyPhoto']").prettyPhoto({animation_speed:'normal',theme:'light_square',slideshow:3000, autoplay_slideshow: true});
        $(".gallery:gt(0) a[rel^='prettyPhoto']").prettyPhoto({animation_speed:'fast',slideshow:10000, hideflash: true});

        $("#custom_content a[rel^='prettyPhoto']:first").prettyPhoto({
            custom_markup: '<div id="map_canvas" style="width:260px; height:265px"></div>',
            changepicturecallback: function(){ initialize(); }
        });

        $("#custom_content a[rel^='prettyPhoto']:last").prettyPhoto({
            custom_markup: '<div id="bsap_1259344" class="bsarocks bsap_d49a0984d0f377271ccbf01a33f2b6d6"></div><div id="bsap_1237859" class="bsarocks bsap_d49a0984d0f377271ccbf01a33f2b6d6" style="height:260px"></div><div id="bsap_1251710" class="bsarocks bsap_d49a0984d0f377271ccbf01a33f2b6d6"></div>',
            changepicturecallback: function(){ _bsap.exec(); }
        });
    });
</script>



<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>