config/routes.rb
Picbook::Application.routes.draw do

  resources :users

  resources :userpanels
  resources :sessions
  resources :password_resets
  resources :albums
  resources :images
  resources :userprofiles

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "usercp" => "users#usercp", :as => "usercp"

  root :to => 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Picbook</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js" type="text/javascript"></script>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    "prettyPhoto", :media => "all" %>
  <%= javascript_include_tag "jquery" %>
  <%= javascript_include_tag "jquery.prettyPhoto" %>

</head>


<body>

<div id="wrapper">
  <div id="header_left"></div>
   <div id="header_right">
    <div id="login">
      <input type="text" value="login" name="login" size="13" />
      <input type="password" value="password" name="password" size="13" />
      <input type="submit" class="imgClass" value=" " name="submit_login" />
    </div>

  </div>
  <div id="content">

      <%= yield %>

  </div>


</div>
</div>

<div id="user_nav">
  <% if current_user %>
      Logged in as <%= current_user.email %>.
      <%= link_to "Log out", log_out_path %>
  <% else %>
      <%= link_to "Sign up", sign_up_path %> or
      <%= link_to "log in", log_in_path %>
  <% end %>
</div>

<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>


</body>
</html>